### ISSUE TITLE
Doesn't work in Alpine Linux

### ISSUE THREAD

**Issue by meelash** [ExplorationSystems/opengpio#19] opened 2024-12-09 23:02 UTC
I'm not sure you'll be able to address this, but for the sake of having it documented, this doesn't seem to build in Alpine Linux (or containers running alpine linux). As far as I can see the Alpine package for libgpiod-dev doesn't have the C++ headers, only C: https://pkgs.alpinelinux.org/contents?name=libgpiod-dev&repo=community&branch=edge&arch=aarch64

This results in the following error when building:
```
error /usr/src/app/node_modules/opengpio: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /usr/src/app/node_modules/opengpio
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@16.20.2 | linux | x64
gyp info find Python using Python version 3.11.11 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/src/app/node_modules/opengpio/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/16.20.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.20.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.20.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/usr/src/app/node_modules/opengpio',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/usr/src/app/node_modules/opengpio/build'
  CXX(target) Release/obj.target/opengpio/cpp/opengpio.o
../cpp/opengpio.cpp:3:10: fatal error: gpiod.hpp: No such file or directory
    3 | #include <gpiod.hpp>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [opengpio.target.mk:113: Release/obj.target/opengpio/cpp/opengpio.o] Error 1
make: Leaving directory '/usr/src/app/node_modules/opengpio/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Linux 6.11.8-300.fc41.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/app/node_modules/opengpio
```

I couldn't figure out a workaround for this.

**Comment by kueckermann** [comment] 2024-12-17 12:15
Thanks @meelash. This might be fixed in the new version 2 i'm working on which doesn't use libgpiod-dev headers but builds the headers when you install. I'm still working out issues with package linking so it's not ready yet (I've had a crazy busy year end and havent had time to finish it), but you can follow the work here: https://github.com/ExplorationSystems/opengpio/issues/1

I'll close this issue for now as if the issue is with libgpiod-dev then I can't address it in this current version 1 of opengpio.

**Closed by kueckermann** 2024-12-17 12:15 UTC
